---
include:
  - "**/*.rb"
  # if pwd = dragonruby-windows-amd64/mygame
  - "app/*.rb"
  - "../../dragonruby-yard-doc/*.rb"
# if pwd = dragonruby-windows-amd64/
# - "mygame/app/*.rb"
# - "../dragonruby-yard-doc/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop # TODO: annoying in sublime text with default rubocop settings, but seems fine in zed..??
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
